# Generated by Django 3.2.13 on 2022-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phubemat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bematcongtrinh',
            options={'ordering': ['id'], 'verbose_name': 'Bề mặt công trình', 'verbose_name_plural': 'Bề mặt công trình'},
        ),
        migrations.AlterModelOptions(
            name='bematkhudancu',
            options={'ordering': ['id'], 'verbose_name': 'Bề mặt khu dân cư', 'verbose_name_plural': 'Bề mặt khu dân cư'},
        ),
        migrations.AlterModelOptions(
            name='caydoclap',
            options={'ordering': ['id'], 'verbose_name': 'Cây độc lập', 'verbose_name_plural': 'Cây độc lập'},
        ),
        migrations.AlterModelOptions(
            name='dattrong',
            options={'ordering': ['id'], 'verbose_name': 'Đất trống', 'verbose_name_plural': 'Đất trống'},
        ),
        migrations.AlterModelOptions(
            name='nuocmat',
            options={'ordering': ['id'], 'verbose_name': 'Nước mặt', 'verbose_name_plural': 'Nước mặt'},
        ),
        migrations.AlterModelOptions(
            name='ranhgioiphubemat',
            options={'ordering': ['id'], 'verbose_name': 'Ranh giới phủ bề mặt', 'verbose_name_plural': 'Ranh giới phủ bề mặt'},
        ),
        migrations.AlterModelOptions(
            name='thucvatdaybien',
            options={'ordering': ['id'], 'verbose_name': 'Thực vật đáy biển', 'verbose_name_plural': 'Thực vật đáy biển'},
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='maDoiTuong',
            field=models.CharField(choices=[('HA01', 'HA01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='bematcongtrinh',
            name='thucVat',
            field=models.IntegerField(choices=[(1, 'Có thực vật che phủ'), (2, 'Không có thực vật che phủ')], verbose_name='Thực vật'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='maDoiTuong',
            field=models.CharField(choices=[('HA02', 'HA02')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='bematkhudancu',
            name='thucVat',
            field=models.IntegerField(choices=[(1, 'Có thực vật che phủ'), (2, 'Không có thực vật che phủ')], verbose_name='Thực vật'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='chieuCao',
            field=models.FloatField(verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='maDoiTuong',
            field=models.CharField(choices=[('HE03', 'Cây độc lập'), ('HE04', 'Cụm cây độc lập')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='caydoclap',
            name='tenCay',
            field=models.CharField(max_length=255, verbose_name='Tên cây'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='maDoiTuong',
            field=models.CharField(choices=[('HC01', 'HC01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='dattrong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='maDoiTuong',
            field=models.CharField(choices=[('HD01', 'HD01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='nuocmat',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='loaiRanhGioiPhuBeMat',
            field=models.IntegerField(choices=[(1, 'Thực vật'), (2, 'Khác'), (3, 'Ranh giới khu bảo tồn thiên nhiên')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='maDoiTuong',
            field=models.CharField(choices=[('HG01', 'HG01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='ranhgioiphubemat',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='maDoiTuong',
            field=models.CharField(choices=[('HK01', 'Cỏ biển'), ('HK02', 'Rong, tảo'), ('HK03', 'Thực vật khác')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='thucvatdaybien',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
    ]
