# Generated by Django 3.2.13 on 2022-08-21 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('maDV', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đơn vị')),
                ('tenDV', models.CharField(max_length=100, verbose_name='Tên đơn vị')),
                ('quanSoDV', models.IntegerField(blank=True, null=True, verbose_name='Quân số đơn vị')),
                ('chucNangDV', models.TextField(blank=True, max_length=500, null=True, verbose_name='Chức năng')),
                ('diaChi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
                ('geoDV', django.contrib.gis.db.models.fields.PointField(srid=4756, verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Đơn vị',
                'verbose_name_plural': 'Đơn vị',
                'ordering': ['maDV'],
            },
        ),
        migrations.CreateModel(
            name='GanLucLuong',
            fields=[
                ('maGanLL', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phương án bố trí lực lượng')),
                ('tenGanLL', models.CharField(max_length=100, verbose_name='Tên phương án bố trí lực lượng')),
                ('noiDungNhiemVuGanLL', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('quanSoGanLL', models.IntegerField(blank=True, null=True, verbose_name='Quân số')),
                ('donViGanLL', models.CharField(max_length=50, verbose_name='Tổ chức, biên chế của lực lượng')),
                ('thoiGianBDau', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('thoiGianKThuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('trangThaiLL', models.IntegerField(choices=[(1, 'Phương án mới, chưa phê duyệt'), (2, 'Phương án mới, đã phê duyệt'), (3, 'Phương án chỉnh sửa, đã phê duyệt'), (4, 'Phương án chỉnh sửa, chưa phê duyệt')], verbose_name='Trạng thái lực lượng')),
            ],
            options={
                'verbose_name': 'Gán lực lượng',
                'verbose_name_plural': 'Gán lực lượng',
                'ordering': ['maGanLL'],
            },
        ),
        migrations.CreateModel(
            name='NVBP',
            fields=[
                ('maNVBP', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã NVBP')),
                ('tenNVBP', models.CharField(max_length=100, verbose_name='Tên NVBP')),
                ('moTaNVBP', models.TextField(max_length=5000, verbose_name='Mô tả NVBP')),
                ('ngayBDNVBP', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ngayKTNVBP', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('trangThaiNVBP', models.IntegerField(choices=[(1, 'Nhiệm vụ giao lần đầu'), (2, 'Nhiệm vụ đã giao và đang giám sát thực hiện'), (3, 'Nhiệm vụ đã kết thúc hoàn thành')], verbose_name='Trạng thái nhiệm vụ')),
                ('maDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_nvbp_dv', to='soanthaokehoach.donvi', verbose_name='Đơn vị')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ bộ phận',
                'verbose_name_plural': 'Nhiệm vụ bộ phận',
                'ordering': ['maNVBP'],
            },
        ),
        migrations.CreateModel(
            name='NVDH',
            fields=[
                ('maNVDH', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã NVDH')),
                ('tenNVDH', models.CharField(max_length=100, verbose_name='Tên NVDH')),
                ('moTaNV', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mô tả NVDH')),
                ('chihuyNVDH', models.CharField(max_length=50, verbose_name='Chỉ huy NVDH')),
                ('ngayBDNVDH', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu NVDH')),
                ('ngayKTNVDH', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc NVDH')),
                ('vanbanNVDH', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Văn bản NVDH')),
                ('kieuNVDH', models.IntegerField(choices=[(1, 'Nhiệm vụ bố trí công trình'), (2, 'Nhiệm vụ tìm kiếm cứu nạn'), (3, 'Nhiệm vụ soạn thảo văn kiện tác chiến'), (4, 'Nhiệm vụ quản lý chất lượng công trình')], verbose_name='Kiểu NVDH')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ điều hành',
                'verbose_name_plural': 'Nhiệm vụ điều hành',
                'ordering': ['maNVDH'],
            },
        ),
        migrations.CreateModel(
            name='VungNVDH',
            fields=[
                ('maVung', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã vùng')),
                ('tenVung', models.CharField(max_length=100)),
                ('moTaVung', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả vùng')),
                ('ngayVung', models.DateField(blank=True, null=True, verbose_name='Ngày thêm, sửa')),
                ('geoVung', django.contrib.gis.db.models.fields.LineStringField(srid=4756, verbose_name='Vùng')),
                ('nvdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vungnvdh_nvdh', to='soanthaokehoach.nvdh', verbose_name='Nhiệm vụ điều hành')),
            ],
            options={
                'verbose_name': 'Vùng NVDH',
                'verbose_name_plural': 'Vùng NVDH',
                'ordering': ['maVung'],
            },
        ),
        migrations.CreateModel(
            name='TuyenNVDH',
            fields=[
                ('maTuyen', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tuyến')),
                ('tenTuyen', models.CharField(max_length=100)),
                ('moTaTuyen', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả tuyến')),
                ('ngayTuyen', models.DateField(blank=True, null=True, verbose_name='Ngày thêm, sửa')),
                ('geoTuyen', django.contrib.gis.db.models.fields.LineStringField(srid=4756, verbose_name='Tuyến')),
                ('nvdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tuyennvdh_nvdh', to='soanthaokehoach.nvdh', verbose_name='Nhiệm vụ điều hành')),
            ],
            options={
                'verbose_name': 'Tuyến NVDH',
                'verbose_name_plural': 'Tuyến NVDH',
                'ordering': ['maTuyen'],
            },
        ),
        migrations.CreateModel(
            name='PhuongAnVung',
            fields=[
                ('maPAVung', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phương án')),
                ('tenPAVung', models.CharField(max_length=100, verbose_name='Tên phương án')),
                ('moTaPAVung', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiPAVung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người thực hiện')),
                ('ngayPAVung', models.DateField(blank=True, null=True, verbose_name='Ngày lựa chọn phương án')),
                ('kieuPAVung', models.IntegerField(choices=[(1, 'Vùng bố trí công trình'), (2, 'Vùng tìm kiếm'), (3, 'Vùng tập kết')], verbose_name='Kiểu phương án')),
                ('trangThaiPAVung', models.IntegerField(choices=[(1, 'Phương án mới, chưa phê duyệt'), (2, 'Phương án mới, đã phê duyệt'), (3, 'Phương án chỉnh sửa, đã phê duyệt'), (4, 'Phương án chỉnh sửa, chưa phê duyệt')], verbose_name='Trạng thái phương án')),
                ('geoPAVung', django.contrib.gis.db.models.fields.PointField(srid=4756, verbose_name='Tuyến đường')),
                ('nvbp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pav_nvbp', to='soanthaokehoach.nvbp', verbose_name='Nhiệm vụ bộ phận')),
            ],
            options={
                'verbose_name': 'Phương án vùng',
                'verbose_name_plural': 'Phương án vùng',
                'ordering': ['maPAVung'],
            },
        ),
        migrations.CreateModel(
            name='PhuongAnViTri',
            fields=[
                ('maPAVT', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phương án')),
                ('tenPAVT', models.CharField(max_length=100, verbose_name='Tên phương án')),
                ('moTaPAVT', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiPAVT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người thực hiện')),
                ('ngayPAVT', models.DateField(blank=True, null=True, verbose_name='Ngày lựa chọn phương án')),
                ('kieuPAVT', models.IntegerField(choices=[(1, 'Điểm bố trí công trình'), (2, 'Điểm xuất phát'), (3, 'Điểm đích')], verbose_name='Kiểu phương án')),
                ('trangthaiPAVT', models.IntegerField(choices=[(1, 'Phương án mới, chưa phê duyệt'), (2, 'Phương án mới, đã phê duyệt'), (3, 'Phương án chỉnh sửa, đã phê duyệt'), (4, 'Phương án chỉnh sửa, chưa phê duyệt')], verbose_name='Trạng thái phương án')),
                ('geoPAVT', django.contrib.gis.db.models.fields.PointField(srid=4756, verbose_name='Vị trí')),
                ('nvbp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pavt_nvbp', to='soanthaokehoach.nvbp', verbose_name='Nhiệm vụ bộ phận')),
            ],
            options={
                'verbose_name': 'Phương án vị trí',
                'verbose_name_plural': 'Phương án vị trí',
                'ordering': ['maPAVT'],
            },
        ),
        migrations.CreateModel(
            name='PhuongAnTuyen',
            fields=[
                ('maPATuyen', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phương án')),
                ('tenPATuyen', models.CharField(max_length=100, verbose_name='Tên phương án')),
                ('moTaPATuyen', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiPATuyen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người thực hiện')),
                ('ngayPATuyen', models.DateField(blank=True, null=True, verbose_name='Ngày lựa chọn phương án')),
                ('kieuPATuyen', models.IntegerField(choices=[(1, 'Tuyến bố trí công trình'), (2, 'Tuyến hành quân')], verbose_name='Kiểu phương án')),
                ('trangThaiPATuyen', models.IntegerField(choices=[(1, 'Phương án mới, chưa phê duyệt'), (2, 'Phương án mới, đã phê duyệt'), (3, 'Phương án chỉnh sửa, đã phê duyệt'), (4, 'Phương án chỉnh sửa, chưa phê duyệt')], verbose_name='Trạng thái phương án')),
                ('geoPATuyen', django.contrib.gis.db.models.fields.PointField(srid=4756, verbose_name='Tuyến đường')),
                ('nvbp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pat_nvbp', to='soanthaokehoach.nvbp', verbose_name='Nhiệm vụ bộ phận')),
            ],
            options={
                'verbose_name': 'Phương án tuyến',
                'verbose_name_plural': 'Phương án tuyến',
                'ordering': ['maPATuyen'],
            },
        ),
        migrations.CreateModel(
            name='PheDuyetPhuongAnVung',
            fields=[
                ('maCMPAVung', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phê duyệt')),
                ('moTaCMPAVung', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiCMPAVung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người phê duyệt')),
                ('ngayCMPAVung', models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('trangThaiCMPAVung', models.IntegerField(choices=[(1, 'Phê duyệt'), (2, 'Chỉnh sửa phương án'), (3, 'Bổ sung phương án')], verbose_name='Trạng thái')),
                ('geoCMPAVung', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756, verbose_name='Góp ý')),
                ('paVung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pdpav_pavt', to='soanthaokehoach.phuonganvung', verbose_name='Phương án vùng')),
            ],
            options={
                'verbose_name': 'Phê duyệt phương án vùng',
                'verbose_name_plural': 'Phê duyệt phương án vùng',
                'ordering': ['maCMPAVung'],
            },
        ),
        migrations.CreateModel(
            name='PheDuyetPhuongAnViTri',
            fields=[
                ('maCMPAVT', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phê duyệt')),
                ('moTaCMPAVT', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiCMPAVT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người phê duyệt')),
                ('ngayCMPAVT', models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('trangThaiCMPAVT', models.IntegerField(choices=[(1, 'Phê duyệt'), (2, 'Chỉnh sửa phương án'), (3, 'Bổ sung phương án')], verbose_name='Trạng thái')),
                ('geoCMPAVT', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756, verbose_name='Góp ý')),
                ('paViTri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pdpavt_pavt', to='soanthaokehoach.phuonganvitri', verbose_name='Phương án vị trí')),
            ],
            options={
                'verbose_name': 'Phê duyệt phương án vị trí',
                'verbose_name_plural': 'Phê duyệt phương án vị trí',
                'ordering': ['maCMPAVT'],
            },
        ),
        migrations.CreateModel(
            name='PheDuyetPhuongAnTuyen',
            fields=[
                ('maCMPATuyen', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phê duyệt')),
                ('moTaCMPATuyen', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('nguoiCMPATuyen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người phê duyệt')),
                ('ngayCMPATuyen', models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('trangThaiCMPATuyen', models.IntegerField(choices=[(1, 'Phê duyệt'), (2, 'Chỉnh sửa phương án'), (3, 'Bổ sung phương án')], verbose_name='Trạng thái')),
                ('geoCMPATuyen', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756, verbose_name='Góp ý')),
                ('paTuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pdpat_pavt', to='soanthaokehoach.phuongantuyen', verbose_name='Phương án tuyến')),
            ],
            options={
                'verbose_name': 'Phê duyệt phương án tuyến',
                'verbose_name_plural': 'Phê duyệt phương án tuyến',
                'ordering': ['maCMPATuyen'],
            },
        ),
        migrations.CreateModel(
            name='PheDuyetPhuongAnGanLucLuong',
            fields=[
                ('maCMGanLL', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phê duyệt')),
                ('cmNoiDungNhiemVuGanLL', models.TextField(max_length=1000, verbose_name='Mô tả')),
                ('cmQuanSoGanLL', models.IntegerField(blank=True, null=True, verbose_name='Quân số')),
                ('cmDonViGanLL', models.TextField(max_length=500, verbose_name='Phê duyệt biên chế lực lượng')),
                ('cmThoiGianBDau', models.DateField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('cmThoiGianKThuc', models.DateField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('trangThaiCMGanLL', models.IntegerField(choices=[(1, 'Phê duyệt'), (2, 'Chỉnh sửa phương án'), (3, 'Bổ sung phương án')], verbose_name='Trạng thái phê duyệt phương án')),
                ('ganLL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pdpagll_ganll', to='soanthaokehoach.ganlucluong', verbose_name='Phương án bố trí lực lượng')),
            ],
            options={
                'verbose_name': 'Phê duyệt phương án gán lực lượng',
                'verbose_name_plural': 'Phê duyệt phương án gán lực lượng',
                'ordering': ['maCMGanLL'],
            },
        ),
        migrations.CreateModel(
            name='PheDuyetChungNVBP',
            fields=[
                ('maCMNVBP', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phê duyệt')),
                ('tenCMNVBP', models.CharField(max_length=50, verbose_name='Tên phê duyệt')),
                ('moTaCMNVBP', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mô tả')),
                ('nguoiCMNVBP', models.TextField(blank=True, max_length=50, null=True, verbose_name='Người phê duyệt')),
                ('ngayCMNVBP', models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('trangThaiCMNVBP', models.IntegerField(choices=[(1, 'Phê duyệt'), (2, 'Chỉnh sửa phương án'), (3, 'Bổ sung phương án'), (4, 'Kết thúc')], verbose_name='Trạng thái')),
                ('nvbp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pdcnvbp_nvbp', to='soanthaokehoach.nvbp', verbose_name='Nhiệm vụ bộ phận')),
            ],
            options={
                'verbose_name': 'Phê duyệt chung NVBP',
                'verbose_name_plural': 'Phê duyệt chung NVBP',
                'ordering': ['maCMNVBP'],
            },
        ),
        migrations.AddField(
            model_name='nvbp',
            name='maNVDH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_nvbp_nvdh', to='soanthaokehoach.nvdh', verbose_name='Nhiệm vụ điều hành'),
        ),
        migrations.AddField(
            model_name='ganlucluong',
            name='pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ganll_pat', to='soanthaokehoach.phuongantuyen', verbose_name='Phương án tuyến'),
        ),
        migrations.AddField(
            model_name='ganlucluong',
            name='pav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ganll_pav', to='soanthaokehoach.phuonganvung', verbose_name='Phương án vùng'),
        ),
        migrations.AddField(
            model_name='ganlucluong',
            name='pavt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ganll_pavt', to='soanthaokehoach.phuonganvitri', verbose_name='Phương án vị trí'),
        ),
        migrations.CreateModel(
            name='DiemNVDH',
            fields=[
                ('maDiem', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã điểm')),
                ('tenDiem', models.CharField(max_length=100, verbose_name='Tên điểm')),
                ('moTaDiem', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả điểm')),
                ('ngayDiem', models.DateField(blank=True, null=True, verbose_name='Ngày thêm, sửa')),
                ('geoDiem', django.contrib.gis.db.models.fields.PointField(srid=4756, verbose_name='Điểm')),
                ('nvdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_diemnvdh_nvdh', to='soanthaokehoach.nvdh', verbose_name='Nhiệm vụ điều hành')),
            ],
            options={
                'verbose_name': 'Điểm NVDH',
                'verbose_name_plural': 'Điểm NVDH',
                'ordering': ['maDiem'],
            },
        ),
    ]
