# Generated by Django 3.2.13 on 2022-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soanthaokehoach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganlucluong',
            name='trangThaiLL',
            field=models.IntegerField(verbose_name='Trạng thái lực lượng'),
        ),
    ]
