# Generated by Django 3.2.13 on 2022-06-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soanthaokehoach', '0002_alter_ganlucluong_trangthaill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phuongantuyen',
            options={'ordering': ['maPATuyen'], 'verbose_name_plural': 'Phương án tuyến'},
        ),
        migrations.AlterModelOptions(
            name='phuonganvung',
            options={'ordering': ['maPAVung'], 'verbose_name_plural': 'Phương án vùng'},
        ),
    ]
