# Generated by Django 3.2.13 on 2022-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soanthaokehoach', '0004_auto_20220711_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diemnvdh',
            options={'ordering': ['maDiem'], 'verbose_name': 'Điểm NVDH', 'verbose_name_plural': 'Điểm NVDH'},
        ),
        migrations.AlterModelOptions(
            name='donvi',
            options={'ordering': ['maDV'], 'verbose_name': 'Đơn vị', 'verbose_name_plural': 'Đơn vị'},
        ),
        migrations.AlterModelOptions(
            name='ganlucluong',
            options={'ordering': ['maGanLL'], 'verbose_name': 'Gán lực lượng', 'verbose_name_plural': 'Gán lực lượng'},
        ),
        migrations.AlterModelOptions(
            name='nvbp',
            options={'ordering': ['maNVBP'], 'verbose_name': 'Nhiệm vụ bộ phận', 'verbose_name_plural': 'Nhiệm vụ bộ phận'},
        ),
        migrations.AlterModelOptions(
            name='nvdh',
            options={'ordering': ['maNVDH'], 'verbose_name': 'Nhiệm vụ điều hành', 'verbose_name_plural': 'Nhiệm vụ điều hành'},
        ),
        migrations.AlterModelOptions(
            name='pheduyetchungnvbp',
            options={'ordering': ['maCMNVBP'], 'verbose_name': 'Phê duyệt chung NVBP', 'verbose_name_plural': 'Phê duyệt chung NVBP'},
        ),
        migrations.AlterModelOptions(
            name='pheduyetphuonganganlucluong',
            options={'ordering': ['maCMGanLL'], 'verbose_name': 'Phê duyệt phương án gán lực lượng', 'verbose_name_plural': 'Phê duyệt phương án gán lực lượng'},
        ),
        migrations.AlterModelOptions(
            name='pheduyetphuongantuyen',
            options={'ordering': ['maCMPATuyen'], 'verbose_name': 'Phê duyệt phương án tuyến', 'verbose_name_plural': 'Phê duyệt phương án tuyến'},
        ),
        migrations.AlterModelOptions(
            name='pheduyetphuonganvitri',
            options={'ordering': ['maCMPAVT'], 'verbose_name': 'Phê duyệt phương án vị trí', 'verbose_name_plural': 'Phê duyệt phương án vị trí'},
        ),
        migrations.AlterModelOptions(
            name='pheduyetphuonganvung',
            options={'ordering': ['maCMPAVung'], 'verbose_name': 'Phê duyệt phương án vùng', 'verbose_name_plural': 'Phê duyệt phương án vùng'},
        ),
        migrations.AlterModelOptions(
            name='phuongantuyen',
            options={'ordering': ['maPATuyen'], 'verbose_name': 'Phương án tuyến', 'verbose_name_plural': 'Phương án tuyến'},
        ),
        migrations.AlterModelOptions(
            name='phuonganvitri',
            options={'ordering': ['maPAVT'], 'verbose_name': 'Phương án vị trí', 'verbose_name_plural': 'Phương án vị trí'},
        ),
        migrations.AlterModelOptions(
            name='phuonganvung',
            options={'ordering': ['maPAVung'], 'verbose_name': 'Phương án vùng', 'verbose_name_plural': 'Phương án vùng'},
        ),
        migrations.AlterModelOptions(
            name='tuyennvdh',
            options={'ordering': ['maTuyen'], 'verbose_name': 'Tuyến NVDH', 'verbose_name_plural': 'Tuyến NVDH'},
        ),
        migrations.AlterModelOptions(
            name='vungnvdh',
            options={'ordering': ['maVung'], 'verbose_name': 'Vung NVDH', 'verbose_name_plural': 'Vung NVDH'},
        ),
        migrations.RenameField(
            model_name='ganlucluong',
            old_name='thoiGianKetThuc',
            new_name='thoiGianKThuc',
        ),
        migrations.RenameField(
            model_name='pheduyetphuonganvung',
            old_name='paTuyen',
            new_name='paVung',
        ),
        migrations.AlterField(
            model_name='ganlucluong',
            name='trangThaiLL',
            field=models.IntegerField(choices=[(1, 'Phương án mới, chưa phê duyệt'), (2, 'Phương án mới, đã phê duyệt'), (3, 'Phương án chỉnh sửa, đã phê duyệt'), (4, 'Phương án chỉnh sửa, chưa phê duyệt')], verbose_name='Trạng thái lực lượng'),
        ),
    ]
