version: "3.9"


services:
  # FRONTEND
  vue:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - ./.env
    restart: always
    ports:
      - "80:80"
