version: "3.9"


services:
  # FRONTEND
  vue:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
