# Generated by Django 3.2.13 on 2022-06-21 07:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDapTrucThang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GN01', 'GN01')], max_length=50)),
                ('viTribaiDap', models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên nóc nhà')])),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaoHieuDanLuongHangHaiDuongThuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GA01', 'Chập tiêu'), ('GA02', 'Đăng tiêu'), ('GA03', 'Phao báo hiệu'), ('GA04', 'Tiêu báo hiệu')], max_length=50)),
                ('coDen', models.BooleanField(default=True)),
                ('huongBaoHieu', models.IntegerField(choices=[(1, 'Trái'), (2, 'Phải'), (3, 'Chuyển hướng trái'), (4, 'Chuyển hướng Phải'), (5, 'Khác')])),
                ('hinhDang', models.IntegerField(choices=[(1, 'Hình tháp'), (2, 'Hình trụ'), (3, 'Hình cầu'), (4, 'Hình cột'), (5, 'Hình trục quay'), (6, 'Hình thùng'), (7, 'Hình tháp lưới'), (8, 'Hình khác'), (9, 'Không xác định')])),
                ('mauSac', models.IntegerField(choices=[(1, 'Trắng'), (2, 'Đen'), (3, 'Đỏ'), (4, 'Xanh lá cây'), (5, 'Xanh da trời'), (6, 'Vàng'), (7, 'Xám'), (8, 'Nâu'), (9, 'Hổ phách'), (10, 'Tím'), (11, 'Cam'), (12, 'Đỏ tươi'), (13, 'Hồng'), (14, 'Đỏ, xanh, đỏ'), (15, 'Xanh, đỏ, xanh'), (16, 'Đỏ, xanh, trắng'), (17, 'Đỏ trắng'), (18, 'Không xác định')])),
                ('phoiHopMauSac', models.IntegerField(choices=[(1, 'Kẻ ngang'), (2, 'Kẻ dọc'), (3, 'Kẻ chéo'), (4, 'Kẻ ô vuông'), (5, 'Kẻ không rõ hướng'), (6, 'Kẻ viền'), (7, 'Không xác định')])),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaoHieuHangHaiAIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GM02', 'GM02')], max_length=50)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BenCang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GM03', 'GM03')], max_length=50)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CacDoiTuongHangHaiHaiVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GC01', 'Cảng dầu khí ngoài khơi'), ('GC02', 'Cọc buộc tàu thuyền'), ('GC03', 'Đăng, chắn đánh bắt cá ổn định'), ('GC04', 'Đèn biển'), ('GC05', 'Khu neo đậu'), ('GC06', 'Khu tránh bão'), ('GC07', 'Khu vực an toàn viện trợ hàng hải'), ('GC08', 'Khu vực bảo tồn thiên nhiên trên biển'), ('GC09', 'Khu vực đánh cá'), ('GC10', 'Khu vực đợi hoa tiêu'), ('GC11', 'Khu vực nạo vét'), ('GC12', 'Khu vực nghiên cứu, khảo sát'), ('GC13', 'Khu vực nguy hiểm'), ('GC14', 'Khu vực quản lý cảng'), ('GC15', 'Khu vực quân sự'), ('GC16', 'Khu vực trung chuyển hàng hóa'), ('GC17', 'Khu vực vùng nước an toàn'), ('GC18', 'Khu vực xác tàu lịch sử'), ('GC19', 'Lồng bè nuôi trồng thủy hải sản'), ('GC20', 'Nhà giàn'), ('GC21', 'Nhà trên biển'), ('GC22', 'Trạm cứu nạn'), ('GC23', 'Trạm nghiệm triều'), ('GC24', 'Tuyến hàng hải'), ('GC25', 'Vùng cấm'), ('GC26', 'Xác tàu đắm')], max_length=50)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CauTau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GM08', 'GM08')], max_length=50)),
                ('loaiCauTau', models.IntegerField(choices=[(1, 'Kết cấu cố định'), (2, 'Kết cấu nổi')])),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CongGiaoThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GG06', 'GG06')], max_length=50)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongBang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GN04', 'GN04')], max_length=50)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GK01', 'Đường chuyên dùng'), ('GK02', 'Đường đô thị'), ('GK03', 'Đường huyện'), ('GK04', 'Đường quốc lộ'), ('GK05', 'Đường tỉnh'), ('GK06', 'Đường xã')], max_length=50)),
                ('loaiDuongBo', models.IntegerField(choices=[(1, 'Đường chính'), (2, 'Đường dẫn'), (3, 'Đường gom'), (4, 'Đường nhánh')])),
                ('capKyThuat', models.IntegerField(choices=[(1, 'Cao tốc'), (2, 'Cấp khác')])),
                ('loaiChatLieuTraiMat', models.IntegerField(choices=[(1, 'Bê tông'), (2, 'Nhựa'), (3, 'Đá, sỏi'), (4, 'Gạch'), (5, 'Đất'), (6, 'Khác')])),
                ('loaiHienTrangSuDung', models.IntegerField(choices=[(1, 'Đang sử dụng'), (2, 'Đang xây dựng'), (3, 'Không sử dụng')])),
                ('chieuXeChay', models.IntegerField(choices=[(1, 'Một chiều'), (2, 'Hai chiều')])),
                ('viTri', models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên cao mức 1'), (3, 'Trên cao mức 2'), (4, 'Trên cao mức 3'), (5, 'Trên cao mức 4'), (6, 'Trên cao mức 5'), (7, 'Ngầm mức 1'), (8, 'Ngầm mức 2')])),
                ('soLanDuong', models.IntegerField()),
                ('chieuRong', models.FloatField()),
                ('ten', models.CharField(max_length=255)),
                ('lienKetGiaoThong', models.IntegerField(choices=[(1, 'Qua cầu'), (2, 'Qua hầm'), (3, 'Trên đê'), (4, 'Qua ngầm'), (5, 'Qua phà đường bộ'), (6, 'Qua đò'), (7, 'Qua bến lội'), (8, 'Qua đập'), (9, 'Khác')])),
                ('tenTuyenGiaoThongXuyenQuocGia', models.CharField(max_length=255)),
                ('tenQuocLo', models.CharField(max_length=255)),
                ('tenDuongTinh', models.CharField(max_length=255)),
                ('tenDuongHuyen', models.CharField(max_length=255)),
                ('tenDuongXa', models.CharField(max_length=255)),
                ('tenDuongDoThi', models.CharField(max_length=255)),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NhomAuTau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('GM01', 'Âu tàu'), ('GM05', 'Bờ xây âu tàu'), ('GM09', 'Cửa âu tàu')], max_length=50)),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
