# Generated by Django 3.2.13 on 2022-08-21 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiDapTrucThang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GN01', 'GN01')], max_length=50, verbose_name='Mã đối tượng')),
                ('viTriBaiDap', models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên nóc nhà')], verbose_name='Vị trí')),
                ('ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên')),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Bãi đáp trực thăng',
                'verbose_name_plural': 'Bãi đáp trực thăng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaoHieuDanLuongHangHaiDuongThuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GA01', 'Chập tiêu'), ('GA02', 'Đăng tiêu'), ('GA03', 'Phao báo hiệu'), ('GA04', 'Tiêu báo hiệu')], max_length=50, verbose_name='Mã đối tượng')),
                ('coDen', models.BooleanField(default=True, verbose_name='Có đèn')),
                ('huongBaoHieu', models.IntegerField(choices=[(1, 'Trái'), (2, 'Phải'), (3, 'Chuyển hướng trái'), (4, 'Chuyển hướng Phải'), (5, 'Khác')], verbose_name='Hướng báo hiệu')),
                ('hinhDang', models.IntegerField(choices=[(1, 'Hình tháp'), (2, 'Hình trụ'), (3, 'Hình cầu'), (4, 'Hình cột'), (5, 'Hình trục quay'), (6, 'Hình thùng'), (7, 'Hình tháp lưới'), (8, 'Hình khác'), (9, 'Không xác định')], verbose_name='Hình dạng')),
                ('mauSac', models.IntegerField(choices=[(1, 'Trắng'), (2, 'Đen'), (3, 'Đỏ'), (4, 'Xanh lá cây'), (5, 'Xanh da trời'), (6, 'Vàng'), (7, 'Xám'), (8, 'Nâu'), (9, 'Hổ phách'), (10, 'Tím'), (11, 'Cam'), (12, 'Đỏ tươi'), (13, 'Hồng'), (14, 'Đỏ, xanh, đỏ'), (15, 'Xanh, đỏ, xanh'), (16, 'Đỏ, xanh, trắng'), (17, 'Đỏ trắng'), (18, 'Không xác định')], verbose_name='Màu sắc')),
                ('phoiHopMauSac', models.IntegerField(choices=[(1, 'Kẻ ngang'), (2, 'Kẻ dọc'), (3, 'Kẻ chéo'), (4, 'Kẻ ô vuông'), (5, 'Kẻ không rõ hướng'), (6, 'Kẻ viền'), (7, 'Không xác định')], verbose_name='Phối hợp màu sắc')),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Báo hiệu dẫn luồng hàng hải đường thuỷ',
                'verbose_name_plural': 'Báo hiệu dẫn luồng hàng hải đường thuỷ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaoHieuHangHaiAIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GM02', 'GM02')], max_length=50, verbose_name='Mã đối tượng')),
                ('ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên')),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Báo hiệu hàng hải AIS',
                'verbose_name_plural': 'Báo hiệu hàng hải AIS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BenCang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GM03', 'GM03')], max_length=50, verbose_name='Mã đối tượng')),
                ('ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên')),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Bến cảng',
                'verbose_name_plural': 'Bến cảng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CacDoiTuongHangHaiHaiVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GC01', 'Cảng dầu khí ngoài khơi'), ('GC02', 'Cọc buộc tàu thuyền'), ('GC03', 'Đăng, chắn đánh bắt cá ổn định'), ('GC04', 'Đèn biển'), ('GC05', 'Khu neo đậu'), ('GC06', 'Khu tránh bão'), ('GC07', 'Khu vực an toàn viện trợ hàng hải'), ('GC08', 'Khu vực bảo tồn thiên nhiên trên biển'), ('GC09', 'Khu vực đánh cá'), ('GC10', 'Khu vực đợi hoa tiêu'), ('GC11', 'Khu vực nạo vét'), ('GC12', 'Khu vực nghiên cứu, khảo sát'), ('GC13', 'Khu vực nguy hiểm'), ('GC14', 'Khu vực quản lý cảng'), ('GC15', 'Khu vực quân sự'), ('GC16', 'Khu vực trung chuyển hàng hóa'), ('GC17', 'Khu vực vùng nước an toàn'), ('GC18', 'Khu vực xác tàu lịch sử'), ('GC19', 'Lồng bè nuôi trồng thủy hải sản'), ('GC20', 'Nhà giàn'), ('GC21', 'Nhà trên biển'), ('GC22', 'Trạm cứu nạn'), ('GC23', 'Trạm nghiệm triều'), ('GC24', 'Tuyến hàng hải'), ('GC25', 'Vùng cấm'), ('GC26', 'Xác tàu đắm')], max_length=50, verbose_name='Mã đối tượng')),
                ('ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên')),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Các đối tượng hàng hải hải văn',
                'verbose_name_plural': 'Các đối tượng hàng hải hải văn',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CauTau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GM08', 'GM08')], max_length=50, verbose_name='Mã đối tượng')),
                ('loaiCauTau', models.IntegerField(choices=[(1, 'Kết cấu cố định'), (2, 'Kết cấu nổi')], verbose_name='Loại')),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Cầu tàu',
                'verbose_name_plural': 'Cầu tàu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CongGiaoThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GG06', 'GG06')], max_length=50, verbose_name='Mã đối tượng')),
                ('ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên')),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Cống giao thông',
                'verbose_name_plural': 'Cống giao thông',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongBang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GN04', 'GN04')], max_length=50, verbose_name='Mã đối tượng')),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Đường băng',
                'verbose_name_plural': 'Đường băng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GK01', 'Đường chuyên dùng'), ('GK02', 'Đường đô thị'), ('GK03', 'Đường huyện'), ('GK04', 'Đường quốc lộ'), ('GK05', 'Đường tỉnh'), ('GK06', 'Đường xã')], max_length=50, verbose_name='Mã đối tượng')),
                ('loaiDuongBo', models.IntegerField(choices=[(1, 'Đường chính'), (2, 'Đường dẫn'), (3, 'Đường gom'), (4, 'Đường nhánh')], verbose_name='Loại')),
                ('capKyThuat', models.IntegerField(choices=[(1, 'Cao tốc'), (2, 'Cấp khác')], verbose_name='Cấp kỹ thuật')),
                ('loaiChatLieuTraiMat', models.IntegerField(choices=[(1, 'Bê tông'), (2, 'Nhựa'), (3, 'Đá, sỏi'), (4, 'Gạch'), (5, 'Đất'), (6, 'Khác')], verbose_name='Loại chất liệu trải mặt')),
                ('loaiHienTrangSuDung', models.IntegerField(choices=[(1, 'Đang sử dụng'), (2, 'Đang xây dựng'), (3, 'Không sử dụng')], verbose_name='Loại hiện trạng sử dụng')),
                ('chieuXeChay', models.IntegerField(choices=[(1, 'Một chiều'), (2, 'Hai chiều')], verbose_name='Chiều xe chạy')),
                ('viTri', models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên cao mức 1'), (3, 'Trên cao mức 2'), (4, 'Trên cao mức 3'), (5, 'Trên cao mức 4'), (6, 'Trên cao mức 5'), (7, 'Ngầm mức 1'), (8, 'Ngầm mức 2')], verbose_name='Vị trí')),
                ('soLanDuong', models.IntegerField(verbose_name='Số làn đường')),
                ('chieuRong', models.FloatField(verbose_name='Chiều rộng')),
                ('ten', models.CharField(max_length=255, verbose_name='Tên')),
                ('lienKetGiaoThong', models.IntegerField(choices=[(1, 'Qua cầu'), (2, 'Qua hầm'), (3, 'Trên đê'), (4, 'Qua ngầm'), (5, 'Qua phà đường bộ'), (6, 'Qua đò'), (7, 'Qua bến lội'), (8, 'Qua đập'), (9, 'Khác')], verbose_name='Liên kết giao thông')),
                ('tenTuyenGiaoThongXuyenQuocGia', models.CharField(max_length=255, verbose_name='Tuyến giao thông xuyên quốc gia')),
                ('tenQuocLo', models.CharField(max_length=255, verbose_name='Tên quốc lộ')),
                ('tenDuongTinh', models.CharField(max_length=255, verbose_name='Tên đường tỉnh')),
                ('tenDuongHuyen', models.CharField(max_length=255, verbose_name='Tên đường huyện')),
                ('tenDuongXa', models.CharField(max_length=255, verbose_name='Tên đường xã')),
                ('tenDuongDoThi', models.CharField(max_length=255, verbose_name='Tên đường đô thị')),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Đường bộ',
                'verbose_name_plural': 'Đường bộ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NhomAuTau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('GM01', 'Âu tàu'), ('GM05', 'Bờ xây âu tàu'), ('GM09', 'Cửa âu tàu')], max_length=50, verbose_name='Mã đối tượng')),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Nhóm Âu tàu',
                'verbose_name_plural': 'Nhóm Âu tàu',
                'ordering': ['id'],
            },
        ),
    ]
