# Generated by Django 3.2.13 on 2022-06-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giaothong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baidaptructhang',
            old_name='viTribaiDap',
            new_name='viTriBaiDap',
        ),
    ]
