# Generated by Django 3.2.13 on 2022-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaothong', '0002_rename_vitribaidap_baidaptructhang_vitribaidap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baidaptructhang',
            options={'ordering': ['id'], 'verbose_name': 'Bãi đáp trực thăng', 'verbose_name_plural': 'Bãi đáp trực thăng'},
        ),
        migrations.AlterModelOptions(
            name='baohieudanluonghanghaiduongthuy',
            options={'ordering': ['id'], 'verbose_name': 'Báo hiệu dẫn luồng hàng hải đường thuỷ', 'verbose_name_plural': 'Báo hiệu dẫn luồng hàng hải đường thuỷ'},
        ),
        migrations.AlterModelOptions(
            name='baohieuhanghaiais',
            options={'ordering': ['id'], 'verbose_name': 'Báo hiệu hàng hải AIS', 'verbose_name_plural': 'Báo hiệu hàng hải AIS'},
        ),
        migrations.AlterModelOptions(
            name='bencang',
            options={'ordering': ['id'], 'verbose_name': 'Bến cảng', 'verbose_name_plural': 'Bến cảng'},
        ),
        migrations.AlterModelOptions(
            name='cacdoituonghanghaihaivan',
            options={'ordering': ['id'], 'verbose_name': 'Các đối tượng hàng hải hải văn', 'verbose_name_plural': 'Các đối tượng hàng hải hải văn'},
        ),
        migrations.AlterModelOptions(
            name='cautau',
            options={'ordering': ['id'], 'verbose_name': 'Cầu tàu', 'verbose_name_plural': 'Cầu tàu'},
        ),
        migrations.AlterModelOptions(
            name='conggiaothong',
            options={'ordering': ['id'], 'verbose_name': 'Cống giao thông', 'verbose_name_plural': 'Cống giao thông'},
        ),
        migrations.AlterModelOptions(
            name='duongbang',
            options={'ordering': ['id'], 'verbose_name': 'Đường băng', 'verbose_name_plural': 'Đường băng'},
        ),
        migrations.AlterModelOptions(
            name='duongbo',
            options={'ordering': ['id'], 'verbose_name': 'Đường bộ', 'verbose_name_plural': 'Đường bộ'},
        ),
        migrations.AlterModelOptions(
            name='nhomautau',
            options={'ordering': ['id'], 'verbose_name': 'Nhóm Âu tàu', 'verbose_name_plural': 'Nhóm Âu tàu'},
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='maDoiTuong',
            field=models.CharField(choices=[('GN01', 'GN01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='baidaptructhang',
            name='viTriBaiDap',
            field=models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên nóc nhà')], verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='coDen',
            field=models.BooleanField(default=True, verbose_name='Có đèn'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='hinhDang',
            field=models.IntegerField(choices=[(1, 'Hình tháp'), (2, 'Hình trụ'), (3, 'Hình cầu'), (4, 'Hình cột'), (5, 'Hình trục quay'), (6, 'Hình thùng'), (7, 'Hình tháp lưới'), (8, 'Hình khác'), (9, 'Không xác định')], verbose_name='Hình dạng'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='huongBaoHieu',
            field=models.IntegerField(choices=[(1, 'Trái'), (2, 'Phải'), (3, 'Chuyển hướng trái'), (4, 'Chuyển hướng Phải'), (5, 'Khác')], verbose_name='Hướng báo hiệu'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='maDoiTuong',
            field=models.CharField(choices=[('GA01', 'Chập tiêu'), ('GA02', 'Đăng tiêu'), ('GA03', 'Phao báo hiệu'), ('GA04', 'Tiêu báo hiệu')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='mauSac',
            field=models.IntegerField(choices=[(1, 'Trắng'), (2, 'Đen'), (3, 'Đỏ'), (4, 'Xanh lá cây'), (5, 'Xanh da trời'), (6, 'Vàng'), (7, 'Xám'), (8, 'Nâu'), (9, 'Hổ phách'), (10, 'Tím'), (11, 'Cam'), (12, 'Đỏ tươi'), (13, 'Hồng'), (14, 'Đỏ, xanh, đỏ'), (15, 'Xanh, đỏ, xanh'), (16, 'Đỏ, xanh, trắng'), (17, 'Đỏ trắng'), (18, 'Không xác định')], verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='baohieudanluonghanghaiduongthuy',
            name='phoiHopMauSac',
            field=models.IntegerField(choices=[(1, 'Kẻ ngang'), (2, 'Kẻ dọc'), (3, 'Kẻ chéo'), (4, 'Kẻ ô vuông'), (5, 'Kẻ không rõ hướng'), (6, 'Kẻ viền'), (7, 'Không xác định')], verbose_name='Phối hợp màu sắc'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='maDoiTuong',
            field=models.CharField(choices=[('GM02', 'GM02')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='baohieuhanghaiais',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='maDoiTuong',
            field=models.CharField(choices=[('GM03', 'GM03')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='bencang',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='maDoiTuong',
            field=models.CharField(choices=[('GC01', 'Cảng dầu khí ngoài khơi'), ('GC02', 'Cọc buộc tàu thuyền'), ('GC03', 'Đăng, chắn đánh bắt cá ổn định'), ('GC04', 'Đèn biển'), ('GC05', 'Khu neo đậu'), ('GC06', 'Khu tránh bão'), ('GC07', 'Khu vực an toàn viện trợ hàng hải'), ('GC08', 'Khu vực bảo tồn thiên nhiên trên biển'), ('GC09', 'Khu vực đánh cá'), ('GC10', 'Khu vực đợi hoa tiêu'), ('GC11', 'Khu vực nạo vét'), ('GC12', 'Khu vực nghiên cứu, khảo sát'), ('GC13', 'Khu vực nguy hiểm'), ('GC14', 'Khu vực quản lý cảng'), ('GC15', 'Khu vực quân sự'), ('GC16', 'Khu vực trung chuyển hàng hóa'), ('GC17', 'Khu vực vùng nước an toàn'), ('GC18', 'Khu vực xác tàu lịch sử'), ('GC19', 'Lồng bè nuôi trồng thủy hải sản'), ('GC20', 'Nhà giàn'), ('GC21', 'Nhà trên biển'), ('GC22', 'Trạm cứu nạn'), ('GC23', 'Trạm nghiệm triều'), ('GC24', 'Tuyến hàng hải'), ('GC25', 'Vùng cấm'), ('GC26', 'Xác tàu đắm')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='cacdoituonghanghaihaivan',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='loaiCauTau',
            field=models.IntegerField(choices=[(1, 'Kết cấu cố định'), (2, 'Kết cấu nổi')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='maDoiTuong',
            field=models.CharField(choices=[('GM08', 'GM08')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='cautau',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='maDoiTuong',
            field=models.CharField(choices=[('GG06', 'GG06')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='conggiaothong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='maDoiTuong',
            field=models.CharField(choices=[('GN04', 'GN04')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongbang',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='capKyThuat',
            field=models.IntegerField(choices=[(1, 'Cao tốc'), (2, 'Cấp khác')], verbose_name='Cấp kỹ thuật'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='chieuRong',
            field=models.FloatField(verbose_name='Chiều rộng'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='chieuXeChay',
            field=models.IntegerField(choices=[(1, 'Một chiều'), (2, 'Hai chiều')], verbose_name='Chiều xe chạy'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='lienKetGiaoThong',
            field=models.IntegerField(choices=[(1, 'Qua cầu'), (2, 'Qua hầm'), (3, 'Trên đê'), (4, 'Qua ngầm'), (5, 'Qua phà đường bộ'), (6, 'Qua đò'), (7, 'Qua bến lội'), (8, 'Qua đập'), (9, 'Khác')], verbose_name='Liên kết giao thông'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='loaiChatLieuTraiMat',
            field=models.IntegerField(choices=[(1, 'Bê tông'), (2, 'Nhựa'), (3, 'Đá, sỏi'), (4, 'Gạch'), (5, 'Đất'), (6, 'Khác')], verbose_name='Loại chất liệu trải mặt'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='loaiDuongBo',
            field=models.IntegerField(choices=[(1, 'Đường chính'), (2, 'Đường dẫn'), (3, 'Đường gom'), (4, 'Đường nhánh')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='loaiHienTrangSuDung',
            field=models.IntegerField(choices=[(1, 'Đang sử dụng'), (2, 'Đang xây dựng'), (3, 'Không sử dụng')], verbose_name='Loại hiện trạng sử dụng'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='maDoiTuong',
            field=models.CharField(choices=[('GK01', 'Đường chuyên dùng'), ('GK02', 'Đường đô thị'), ('GK03', 'Đường huyện'), ('GK04', 'Đường quốc lộ'), ('GK05', 'Đường tỉnh'), ('GK06', 'Đường xã')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='soLanDuong',
            field=models.IntegerField(verbose_name='Số làn đường'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='ten',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenDuongDoThi',
            field=models.CharField(max_length=255, verbose_name='Tên đường đô thị'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenDuongHuyen',
            field=models.CharField(max_length=255, verbose_name='Tên đường huyện'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenDuongTinh',
            field=models.CharField(max_length=255, verbose_name='Tên đường tỉnh'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenDuongXa',
            field=models.CharField(max_length=255, verbose_name='Tên đường xã'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenQuocLo',
            field=models.CharField(max_length=255, verbose_name='Tên quốc lộ'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='tenTuyenGiaoThongXuyenQuocGia',
            field=models.CharField(max_length=255, verbose_name='Tuyến giao thông xuyên quốc gia'),
        ),
        migrations.AlterField(
            model_name='duongbo',
            name='viTri',
            field=models.IntegerField(choices=[(1, 'Trên mặt đất'), (2, 'Trên cao mức 1'), (3, 'Trên cao mức 2'), (4, 'Trên cao mức 3'), (5, 'Trên cao mức 4'), (6, 'Trên cao mức 5'), (7, 'Ngầm mức 1'), (8, 'Ngầm mức 2')], verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='maDoiTuong',
            field=models.CharField(choices=[('GM01', 'Âu tàu'), ('GM05', 'Bờ xây âu tàu'), ('GM09', 'Cửa âu tàu')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='nhomautau',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
    ]
