# Generated by Django 3.2.13 on 2022-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congtrinhanninh',
            options={'ordering': ['id'], 'verbose_name': 'Công trình an ninh', 'verbose_name_plural': 'Công trình an ninh'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhcongnghiep',
            options={'ordering': ['id'], 'verbose_name': 'Công trình công nghiệp', 'verbose_name_plural': 'Công trình công nghiệp'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhgiaoduc',
            options={'ordering': ['id'], 'verbose_name': 'Công trình giáo dục', 'verbose_name_plural': 'Công trình giáo dục'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhphutro',
            options={'ordering': ['id'], 'verbose_name': 'Công trình phụ trợ', 'verbose_name_plural': 'Công trình phụ trợ'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhquocphong',
            options={'ordering': ['id'], 'verbose_name': 'Công trình quốc phòng', 'verbose_name_plural': 'Công trình quốc phòng'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhthethao',
            options={'ordering': ['id'], 'verbose_name': 'Công trình thể thao', 'verbose_name_plural': 'Công trình thể thao'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhthuongmaidichvu',
            options={'ordering': ['id'], 'verbose_name': 'Công trình thương mại dịch vụ', 'verbose_name_plural': 'Công trình thương mại dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhtongiaotinnguong',
            options={'ordering': ['id'], 'verbose_name': 'Công trình tôn giáo tín ngưỡng', 'verbose_name_plural': 'Công trình tôn giáo tín ngưỡng'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhvanhoa',
            options={'ordering': ['id'], 'verbose_name': 'Công trình văn hoá', 'verbose_name_plural': 'Công trình văn hoá'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhxulychatthai',
            options={'ordering': ['id'], 'verbose_name': 'Công trình xử lý chát thải', 'verbose_name_plural': 'Công trình xử lý chát thải'},
        ),
        migrations.AlterModelOptions(
            name='congtrinhyte',
            options={'ordering': ['id'], 'verbose_name': 'Công trình y tế', 'verbose_name_plural': 'Công trình y tế'},
        ),
        migrations.AlterModelOptions(
            name='cososanxuatnonglamnghiep',
            options={'ordering': ['id'], 'verbose_name': 'Cơ sở sản xuất nông lâm nghiệp', 'verbose_name_plural': 'Cơ sở sản xuất nông lâm nghiệp'},
        ),
        migrations.AlterModelOptions(
            name='cotdien',
            options={'ordering': ['id'], 'verbose_name': 'Cột điện', 'verbose_name_plural': 'Cột điện'},
        ),
        migrations.AlterModelOptions(
            name='diadanhdancu',
            options={'ordering': ['id'], 'verbose_name': 'Địa danh dân cư', 'verbose_name_plural': 'Địa danh dân cư'},
        ),
        migrations.AlterModelOptions(
            name='duongdaytaidien',
            options={'ordering': ['id'], 'verbose_name': 'Đường dây tải điện', 'verbose_name_plural': 'Đường dây tải điện'},
        ),
        migrations.AlterModelOptions(
            name='duongongdan',
            options={'ordering': ['id'], 'verbose_name': 'Đường ống dẫn', 'verbose_name_plural': 'Đường ống dẫn'},
        ),
        migrations.AlterModelOptions(
            name='hatangkythuatkhac',
            options={'ordering': ['id'], 'verbose_name': 'Hạ tầng kỹ thuật khác', 'verbose_name_plural': 'Hạ tầng kỹ thuật khác'},
        ),
        migrations.AlterModelOptions(
            name='khoinha',
            options={'ordering': ['id'], 'verbose_name': 'Khối nhà', 'verbose_name_plural': 'Khối nhà'},
        ),
        migrations.AlterModelOptions(
            name='khuchucnangdacthu',
            options={'ordering': ['id'], 'verbose_name': 'Khu chức năng đặc thù', 'verbose_name_plural': 'Khu chức năng đặc thù'},
        ),
        migrations.AlterModelOptions(
            name='khudancu',
            options={'ordering': ['id'], 'verbose_name': 'Khu dân cư', 'verbose_name_plural': 'Khu dân cư'},
        ),
        migrations.AlterModelOptions(
            name='nha',
            options={'ordering': ['id'], 'verbose_name': 'Nhà', 'verbose_name_plural': 'Nhà'},
        ),
        migrations.AlterModelOptions(
            name='ranhgioi',
            options={'ordering': ['id'], 'verbose_name': 'Ranh giới', 'verbose_name_plural': 'Ranh giới'},
        ),
        migrations.AlterModelOptions(
            name='tramkhituongthuyvanquocgia',
            options={'ordering': ['id'], 'verbose_name': 'Trạm khí tượng thuỷ văn quốc gia', 'verbose_name_plural': 'Trạm khí tượng thuỷ văn quốc gia'},
        ),
        migrations.AlterModelOptions(
            name='tramquantracmoitruong',
            options={'ordering': ['id'], 'verbose_name': 'Trạm quan trắc môi trường', 'verbose_name_plural': 'Trạm quan trắc môi trường'},
        ),
        migrations.AlterModelOptions(
            name='tramquantractainguyennuoc',
            options={'ordering': ['id'], 'verbose_name': 'Trạm quan trắc tài nguyên nước', 'verbose_name_plural': 'Trạm quan trắc tài nguyên nước'},
        ),
        migrations.AlterModelOptions(
            name='trusocoquannhanuoc',
            options={'ordering': ['id'], 'verbose_name': 'Trụ sở cơ quan nhà nước', 'verbose_name_plural': 'Trụ sở cơ quan nhà nước'},
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='maDoiTuong',
            field=models.CharField(choices=[('CC01', 'Đồn công an'), ('CC02', 'Trụ sở công an'), ('CC03', 'Trại cải tạo'), ('CC04', 'Trung tâm phòng cháy chữa cháy')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhanninh',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='loaiCongTrinhCongNghiep',
            field=models.IntegerField(choices=[(1, 'Sản xuất vật liệu xây dựng'), (2, 'Luyện kim và cơ khí chế tạo'), (3, 'Khai thác mỏ và chế biến khoáng sản'), (4, 'Dầu khí'), (5, 'Năng lượng'), (6, 'Hóa chất'), (7, 'Công nghiệp thực phẩm'), (8, 'Công nghiệp tiêu dùng'), (9, 'Công nghiệp chế biến nông, thủy và hải sản')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='maDoiTuong',
            field=models.CharField(choices=[('CD01', 'Bể chứa nhiên liệu'), ('CD02', 'Công trình thủy điện'), ('CD03', 'Cột tháp điện gió'), ('CD04', 'Cửa hầm lò của mỏ'), ('CD05', 'Giàn khoan, tháp khai thác'), ('CD06', 'Kho'), ('CD07', 'Khu khai thác'), ('CD08', 'Lò nung'), ('CD09', 'Nhà máy'), ('CD10', 'Ống khói'), ('CD11', 'Trạm biến áp'), ('CD12', 'Trạm chiết khí hóa lỏng')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhcongnghiep',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='maDoiTuong',
            field=models.CharField(choices=[('CE01', 'Trung tâm giáo dục thường xuyên'), ('CE02', 'Trung tâm kỹ thuật tổng hợp - hướng nghiệp'), ('CE03', 'Trường cao đẳng'), ('CE04', 'Trường đại học'), ('CE05', 'Trường dân tộc nội trú'), ('CE06', 'Trường dạy nghề'), ('CE07', 'Trường giáo dưỡng'), ('CE08', 'Trường mầm non'), ('CE09', 'Trường phổ thông có nhiều cấp học'), ('CE10', 'Trường phổ thông năng khiếu'), ('CE11', 'Trường tiểu học'), ('CE12', 'Trường trung học cơ sở'), ('CE13', 'Trường trung học phổ thông')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhgiaoduc',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='maDoiTuong',
            field=models.CharField(choices=[('CG01', 'Bậc thềm'), ('CG02', 'Cầu thang ngoài trời'), ('CG03', 'Hành lang'), ('CG04', 'Lối xuống tầng hầm')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhphutro',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='maDoiTuong',
            field=models.CharField(choices=[('CH01', 'Cửa khẩu'), ('CH02', 'Doanh trại quân đội'), ('CH03', 'Trụ sở quốc phòng')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhquocphong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='maDoiTuong',
            field=models.CharField(choices=[('CK01', 'Bể bơi'), ('CK02', 'Nhà thi đấu'), ('CK03', 'Sân gôn'), ('CK04', 'Sân thể thao'), ('CK05', 'Sân vận động'), ('CK06', 'Trung tâm thể dục thể thao'), ('CK07', 'Trường đua, trường bắn')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhthethao',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='maDoiTuong',
            field=models.CharField(choices=[('CL01', 'Bãi tắm'), ('CL02', 'Bưu cục'), ('CL03', 'Bưu điện'), ('CL04', 'Các công trình dịch vụ khác'), ('CL05', 'Chợ'), ('CL06', 'Cửa hàng'), ('CL07', 'Điểm bưu điện - văn hóa xã'), ('CL08', 'Khách sạn'), ('CL09', 'Ngân hàng'), ('CL10', 'Nhà hàng'), ('CL11', 'Nhà khách'), ('CL12', 'Nhà lắp đặt thiết bị thông tin'), ('CL13', 'Siêu thị'), ('CL15', 'Trạm xăng, dầu'), ('CL16', 'Trung tâm thương mại')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhthuongmaidichvu',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='maDoiTuong',
            field=models.CharField(choices=[('CM01', 'Chùa'), ('CM02', 'Cơ sở đào tạo tôn giáo'), ('CM03', 'Công trình tôn giáo khác'), ('CM04', 'Đền'), ('CM05', 'Đình'), ('CM06', 'Gác chuông'), ('CM07', 'MiếU'), ('CM08', 'Nhà nguyện'), ('CM09', 'Nhà thờ'), ('CM10', 'Niệm phật đường'), ('CM11', 'Thánh đường'), ('CM12', 'Thánh thất'), ('CM13', 'Trụ sở của tổ chức tôn giáo'), ('CM14', 'Từ đường')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhtongiaotinnguong',
            name='xepHangDiTich',
            field=models.IntegerField(choices=[(1, 'Di tích cấp quốc gia đặc biệt'), (2, 'Di tích cấp quốc gia'), (3, 'Di tích cấp tỉnh'), (4, 'Chưa xếp hạng di tích')], verbose_name='Xếp hạng di tích'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='chieuCao',
            field=models.FloatField(blank=True, null=True, verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='maDoiTuong',
            field=models.CharField(choices=[('CN01', 'Bảo tàng'), ('CN02', 'Chòi cao, tháp cao'), ('CN03', 'Cổng'), ('CN04', 'Công trình di tích'), ('CN05', 'Công trình vui chơi, giải trí'), ('CN06', 'Công viên'), ('CN07', 'Cột cờ'), ('CN08', 'Cột đồng hồ'), ('CN09', 'Đài phun nước'), ('CN10', 'Đài tưởng niệm'), ('CN11', 'Lăng tẩm'), ('CN12', 'Lô cốt'), ('CN13', 'Nhà hát'), ('CN14', 'Nhà văn hóa'), ('CN15', 'Quảng trường'), ('CN16', 'Rạp chiếu phim'), ('CN17', 'Rạp xiếc'), ('CN18', 'Tháp cổ'), ('CN19', 'Thư viện'), ('CN20', 'Triển lãm'), ('CN21', 'Trung tâm hội nghị'), ('CN22', 'Tượng đài'), ('CN23', 'Vườn hoa')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhvanhoa',
            name='xepHangDiTich',
            field=models.IntegerField(choices=[(1, 'Di tích cấp quốc gia đặc biệt'), (2, 'Di tích cấp quốc gia'), (3, 'Di tích cấp tỉnh'), (4, 'Chưa xếp hạng di tích')], verbose_name='Xếp hạng di tích'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='maDoiTuong',
            field=models.CharField(choices=[('CO01', 'Bãi chôn lấp rác'), ('CO02', 'Cơ sở xử lý chất thải nguy hại'), ('CO03', 'Cơ sở xử lý chất thải rắn'), ('CO04', 'Cơ sở xử lý nước thải'), ('CO05', 'Khu xử lý chất thải'), ('CO06', 'Trạm trung chuyển chất thải rắn')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhxulychatthai',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='capYTe',
            field=models.IntegerField(choices=[(1, 'Hạng đặc biệt'), (2, 'Hạng 1'), (3, 'Hạng 2'), (4, 'Hạng 3'), (5, 'Hạng 4')], verbose_name='Cấp y tế'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='maDoiTuong',
            field=models.CharField(choices=[('CP01', 'Bệnh viện'), ('CP02', 'Cơ sở phòng chống dịch bệnh'), ('CP03', 'Cơ sở y tế khác'), ('CP04', 'Nhà hộ sinh'), ('CP05', 'Phòng khám'), ('CP06', 'Trạm y tế'), ('CP07', 'Trung tâm điều dưỡng'), ('CP08', 'Trung tâm y tế')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='congtrinhyte',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='maDoiTuong',
            field=models.CharField(choices=[('CB01', 'Cơ sở sản xuất giống cây, con'), ('CB02', 'Guồng nước'), ('CB03', 'Khu nuôi trồng thủy sản'), ('CB04', 'Lâm trường'), ('CB05', 'Nông trường'), ('CB06', 'Ruộng muối'), ('CB07', 'Trang trại')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='cososanxuatnonglamnghiep',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR06', 'CR06')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='cotdien',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='danhTuChung',
            field=models.IntegerField(choices=[(1, 'Ấp'), (2, 'Bản'), (3, 'Buôn'), (4, 'Chòm'), (5, 'Khu dân cư'), (6, 'Khu tập thể'), (7, 'Khu đô thị'), (8, 'Làng'), (9, 'Lũng'), (10, 'Plei'), (11, 'Tổ dân phố'), (12, 'Trại'), (13, 'Xóm'), (27, 'Thôn'), (28, 'Cụm dân cư'), (29, 'Khóm'), (30, 'Khối phố'), (31, 'Khu phố'), (32, 'Tổ dân cư')], verbose_name='Danh từ chung'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='maDoiTuong',
            field=models.CharField(choices=[('DA02', 'DA02')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='diadanhdancu',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='dienAp',
            field=models.FloatField(verbose_name='Điện áp'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR09', 'CR09')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongdaytaidien',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='loaiOngDan',
            field=models.IntegerField(choices=[(1, 'Nước'), (2, 'Khí'), (3, 'Dầu')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR11', 'CR11')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongongdan',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='chieuCao',
            field=models.FloatField(blank=True, null=True, verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR01', 'Cơ sở hỏa táng'), ('CR02', 'Công trình đang xây dựng'), ('CR03', 'Công trình xử lý bùn'), ('CR04', 'Công trình xử lý nước sạch'), ('CR05', 'Cột đèn chiếu sáng'), ('CR13', 'Họng nước chữa cháy'), ('CR14', 'Mộ độc lập'), ('CR15', 'Nghĩa trang'), ('CR16', 'Nghĩa trang liệt sỹ'), ('CR17', 'Nhà máy nước'), ('CR18', 'Nhà tang lễ'), ('CR19', 'Tháp nước, bể nước'), ('CR23', 'Trạm thu phát sóng')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='hatangkythuatkhac',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='maDoiTuong',
            field=models.CharField(choices=[('CA01', 'CA01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='nhomChieuCao',
            field=models.IntegerField(choices=[(1, 'Đặc biệt'), (2, 'Cấp I'), (3, 'Cấp II'), (4, 'Cấp III'), (5, 'Cấp IV')], verbose_name='Nhóm chiều cao'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='nhomSoTang',
            field=models.IntegerField(choices=[(1, 'Đặc biệt'), (2, 'Cấp I'), (3, 'Cấp II'), (4, 'Cấp III'), (5, 'Cấp IV')], verbose_name='Nhóm số tầng'),
        ),
        migrations.AlterField(
            model_name='khoinha',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='maDoiTuong',
            field=models.CharField(choices=[('CT01', 'Khu chế xuất'), ('CT02', 'Khu công nghệ cao'), ('CT03', 'Khu công nghiệp'), ('CT04', 'Khu du lịch'), ('CT05', 'Khu kinh tế'), ('CT06', 'Khu nghiên cứu đào tạo'), ('CT07', 'Khu thể dục thể thao')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='khuchucnangdacthu',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='loaiKhuDanCu',
            field=models.IntegerField(choices=[(1, 'Đô thị'), (2, 'Nông thôn')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='maDoiTuong',
            field=models.CharField(choices=[('CA02', 'CA02')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='soDan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số dân'),
        ),
        migrations.AlterField(
            model_name='khudancu',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='chieuCao',
            field=models.FloatField(verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='diaChi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='loaiNha',
            field=models.IntegerField(choices=[(1, 'Chung cư'), (2, 'Nhà riêng'), (3, 'An ninh, Quốc phòng'), (4, 'Cơ quan nhà nước'), (5, 'Trụ sở làm việc'), (6, 'Hỗn hợp'), (7, 'Nhà công trình công cộng'), (8, 'Nhà công trình công nghiệp'), (9, 'Nhà công trình hạ tầng kỹ thuật'), (10, 'Nhà cơ sở sản xuất nông lâm nghiệp'), (11, 'Nhà khu chức năng đặc thù'), (12, 'Nhà phụ trọ dân sinh')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='maDoiTuong',
            field=models.CharField(choices=[('CA04', 'CA04')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='mucDoKienCo',
            field=models.IntegerField(choices=[(1, 'Kiên cố'), (2, 'Bán kiên cố'), (3, 'Không kiên cố'), (4, 'Đơn sơ')], verbose_name='Mức độ kiên cố'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='soTang',
            field=models.IntegerField(verbose_name='Số tầng'),
        ),
        migrations.AlterField(
            model_name='nha',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='loaiRanhGioi',
            field=models.IntegerField(choices=[('CU01', 'Hàng rào'), ('CU02', 'Ranh giới khu cấm'), ('CU03', 'Ranh giới sử dụng đất'), ('CU04', 'Thành lũy'), ('CU05', 'Tường vây')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='maDoiTuong',
            field=models.CharField(max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='ranhgioi',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='loaiTramKhiTuongThuyVan',
            field=models.IntegerField(choices=[(1, 'Trạm khí tượng bề mặt'), (2, 'Trạm khí tượng trên cao'), (3, 'Trạm ra đa thời tiết'), (4, 'Trạm khí tượng nông nghiệp'), (5, 'Trạm thủy văn'), (6, 'Trạm hải văn'), (7, 'Trạm đo mưa'), (8, 'Trạm định vị sét'), (9, 'Trạm giám sát biến đổi khí hậu'), (10, 'Trạm chuyên đề')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR20', 'CR20')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramkhituongthuyvanquocgia',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR21', 'CR21')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramquantracmoitruong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('CR22', 'CR22')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramquantractainguyennuoc',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('CV01', 'Cơ quan chuyên môn'), ('CV02', 'Cơ quan Đảng'), ('CV03', 'Toà án'), ('CV04', 'Trụ sở các Bộ'), ('CV05', 'Trụ sở Chính Phủ'), ('CV06', 'Trụ sở tổ chức chính trị - xã hội'), ('CV07', 'Trụ sở UBND cấp Huyện'), ('CV08', 'Trụ sở UBND cấp Tỉnh'), ('CV09', 'Trụ sở UBND cấp Xã'), ('CV10', 'Viện kiểm sát')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='trusocoquannhanuoc',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
    ]
