# Generated by Django 3.2.13 on 2022-08-21 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPhanHanhChinhTrenBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('AE01', 'Địa phận hành chính cấp huyện trên biển'), ('AE02', 'Địa phận hành chính cấp tỉnh trên biển'), ('AE03', 'Địa phận hành chính cấp xã trên biển')], max_length=50, verbose_name='Mã đối tượng')),
                ('maDonViHanhChinh', models.CharField(max_length=20, verbose_name='Mã đơn vị hành chính')),
                ('ten', models.CharField(max_length=255, verbose_name='Tên')),
                ('dientich', models.FloatField(blank=True, null=True, verbose_name='Diện tích')),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Địa phận hành chính trên biển',
                'verbose_name_plural': 'Địa phận hành chính trên biển',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongRanhGioiHanhChinhTrenBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('AE04', 'Đường ranh giới hành chính cấp huyện trên biển'), ('AE05', 'Đường ranh giới hành chính cấp tỉnh trên biển'), ('AE05', 'Đường ranh giới hành chính cấp xã trên biển')], max_length=50, verbose_name='Mã đối tượng')),
                ('loaiHienTrangPhapLy', models.IntegerField(choices=[(1, 'Xác định'), (0, 'Chưa xác định')], verbose_name='Loại hiện trạng pháp lý')),
                ('chieuDai', models.FloatField(verbose_name='Chiều dài')),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Đường ranh giới hành chính trên biển',
                'verbose_name_plural': 'Đường ranh giới hành chính trên biển',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VungBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50, verbose_name='Mã nhận dạng')),
                ('phienBan', models.IntegerField(verbose_name='Phiên bản')),
                ('ngayPhienBan', models.DateTimeField(verbose_name='Ngày phiên bản')),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng')),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi')),
                ('maDoiTuong', models.CharField(choices=[('AB07', 'Lãnh hải'), ('AB11', 'Vùng nội thuỷ'), ('AB12', 'Vùng nước lịch sử'), ('AB13', 'Vùng tiếp giáp lãnh hải')], max_length=50, verbose_name='Mã đối tượng')),
                ('dientich', models.FloatField(blank=True, null=True, verbose_name='Diện tích')),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'verbose_name': 'Vùng biển',
                'verbose_name_plural': 'Vùng biển',
                'ordering': ['id'],
            },
        ),
    ]
