# Generated by Django 3.2.13 on 2022-06-21 07:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPhanHanhChinhTrenBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('AE01', 'Địa phận hành chính cấp huyện trên biển'), ('AE02', 'Địa phận hành chính cấp tỉnh trên biển'), ('AE03', 'Địa phận hành chính cấp xã trên biển')], max_length=50)),
                ('maDonViHanhChinh', models.CharField(max_length=20)),
                ('ten', models.CharField(max_length=255)),
                ('dientich', models.FloatField(blank=True, null=True)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuongRanhGioiHanhChinhTrenBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('AE04', 'Đường ranh giới hành chính cấp huyện trên biển'), ('AE05', 'Đường ranh giới hành chính cấp tỉnh trên biển'), ('AE05', 'Đường ranh giới hành chính cấp xã trên biển')], max_length=50)),
                ('loaiHienTrangPhapLy', models.IntegerField(choices=[(1, 'Xác định'), (0, 'Chưa xác định')])),
                ('chieuDai', models.FloatField()),
                ('GM_Curve', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VungBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('maDoiTuong', models.CharField(choices=[('AB07', 'Lãnh hải'), ('AB11', 'Vùng nội thuỷ'), ('AB12', 'Vùng nước lịch sử'), ('AB13', 'Vùng tiếp giáp lãnh hải')], max_length=50)),
                ('dientich', models.FloatField(blank=True, null=True)),
                ('GM_Surface', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4756)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
