# Generated by Django 3.2.13 on 2022-06-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biengioidiagioi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vungbien',
            options={'ordering': ['id'], 'verbose_name_plural': 'Vùng biển'},
        ),
    ]
