# Generated by Django 3.2.13 on 2022-07-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thuyvan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiboi',
            options={'ordering': ['id'], 'verbose_name': 'Bãi bồi', 'verbose_name_plural': 'Bãi bồi'},
        ),
        migrations.AlterModelOptions(
            name='baidaduoinuoc',
            options={'ordering': ['id'], 'verbose_name': 'Bãi đá dưới nước', 'verbose_name_plural': 'Bãi đá dưới nước'},
        ),
        migrations.AlterModelOptions(
            name='biendao',
            options={'ordering': ['id'], 'verbose_name': 'Biển đảo', 'verbose_name_plural': 'Biển đảo'},
        ),
        migrations.AlterModelOptions(
            name='bokebocap',
            options={'ordering': ['id'], 'verbose_name': 'Bờ kè bờ cạp', 'verbose_name_plural': 'Bờ kè bờ cạp'},
        ),
        migrations.AlterModelOptions(
            name='dao',
            options={'ordering': ['id'], 'verbose_name': 'Đảo', 'verbose_name_plural': 'Đảo'},
        ),
        migrations.AlterModelOptions(
            name='diemdocaomucnuoc',
            options={'ordering': ['id'], 'verbose_name': 'Điểm độ cao mực nước', 'verbose_name_plural': 'Điểm độ cao mực nước'},
        ),
        migrations.AlterModelOptions(
            name='duongbonuoc',
            options={'ordering': ['id'], 'verbose_name': 'Đường bờ nước', 'verbose_name_plural': 'Đường bờ nước'},
        ),
        migrations.AlterModelOptions(
            name='duongmepnuoc',
            options={'ordering': ['id'], 'verbose_name': 'Đường mép nước', 'verbose_name_plural': 'Đường mép nước'},
        ),
        migrations.AlterModelOptions(
            name='kenhmuong',
            options={'ordering': ['id'], 'verbose_name': 'Kênh mương', 'verbose_name_plural': 'Kênh mương'},
        ),
        migrations.AlterModelOptions(
            name='nguonnuoc',
            options={'ordering': ['id'], 'verbose_name': 'Nguồn nước', 'verbose_name_plural': 'Nguồn nước'},
        ),
        migrations.AlterModelOptions(
            name='ranhgioinuocmatquyuoc',
            options={'ordering': ['id'], 'verbose_name': 'Ranh giới nước mặt quy ước', 'verbose_name_plural': 'Ranh giới nước mặt quy ước'},
        ),
        migrations.AlterModelOptions(
            name='songgiodongchay',
            options={'ordering': ['id'], 'verbose_name': 'Số liệu sóng, gió, dòng chảy', 'verbose_name_plural': 'Số liệu sóng, gió, dòng chảy'},
        ),
        migrations.AlterModelOptions(
            name='thamsokttv',
            options={'ordering': ['id'], 'verbose_name': 'Tham số KTTV', 'verbose_name_plural': 'Tham số KTTV'},
        ),
        migrations.AlterModelOptions(
            name='thamsonuoc',
            options={'ordering': ['id'], 'verbose_name': 'Tham số nước', 'verbose_name_plural': 'Tham số nước'},
        ),
        migrations.AlterModelOptions(
            name='tramthuthapkttv',
            options={'ordering': ['id'], 'verbose_name': 'Trạm thu thập TTTV', 'verbose_name_plural': 'Trạm thu thập TTTV'},
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='loaiBaiBoi',
            field=models.IntegerField(choices=[(1, 'Cát'), (2, 'Bùn'), (3, 'Loại khác')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='maDoiTuong',
            field=models.CharField(choices=[('KB01', 'KB01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='baiboi',
            name='trangThaiXuatLo',
            field=models.IntegerField(choices=[(1, 'Chìm'), (2, 'Nổi'), (3, 'Lúc nổi, lúc chìm'), (4, 'Không xác định')], verbose_name='Trạng thái xuất lô'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KC01', 'Bãi đá dưới nước'), ('KC02', 'Đá trên biển'), ('KC03', 'San hô')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='baidaduoinuoc',
            name='trangThaiXuatLo',
            field=models.IntegerField(choices=[(1, 'Chìm'), (2, 'Nổi'), (3, 'Lúc nổi, lúc chìm'), (4, 'Không xác định')], verbose_name='Trạng thái xuất lô'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='maDoiTuong',
            field=models.CharField(choices=[('KA01', 'Biển'), ('KA02', 'Đảo, quần đảo'), ('KA03', 'Phá'), ('KA04', 'Vịnh, vũng')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='biendao',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='loaiChatLieu',
            field=models.IntegerField(choices=[(1, 'Bê tông'), (2, 'Đá sỏi'), (3, 'Khác')], verbose_name='Loại chất liệU'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='loaiThanhPhan',
            field=models.IntegerField(choices=[(1, 'Chân'), (2, 'Đỉnh')], verbose_name='Loại thành phần'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='maDoiTuong',
            field=models.CharField(choices=[('KG01', 'KG01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='bokebocap',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='loaiTrangThaiXuatLo',
            field=models.IntegerField(choices=[(1, 'Chìm'), (2, 'Nổi'), (3, 'Nửa chìm, nửa nổi')], verbose_name='Loại trạng thái xuất lô'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='maDoiTuong',
            field=models.CharField(max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='ten',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='doCao',
            field=models.FloatField(verbose_name='Độ cao'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KE01', 'KE01')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='diemdocaomucnuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='loaiDuongBoNuoc',
            field=models.IntegerField(choices=[(1, 'Ao, hồ, đầm'), (2, 'Phá'), (3, 'Kênh, mương'), (4, 'Hồ chứa'), (5, 'Sông, suối'), (6, 'Biển')], verbose_name='Loại đường bờ nước'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='loaiTrangThaiDuongBoNuoc',
            field=models.IntegerField(choices=[(1, 'Rõ ràng'), (2, 'Khó xác định'), (3, 'Đường bờ sông suối có nước theo mùa')], verbose_name='Loại trạng thái'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KE03', 'KE03')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongbonuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='loaiDuongMepNuoc',
            field=models.IntegerField(choices=[(1, 'Ao, hồ, đầm'), (2, 'Phá'), (3, 'Kênh, mương'), (4, 'Hồ chứa'), (5, 'Sông, suối'), (6, 'Biển'), (7, 'Triều kiệt')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KE05', 'KE05')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='duongmepnuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='chieuRong',
            field=models.FloatField(verbose_name='Chiều rộng'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='loaiHienTrangSuDung',
            field=models.IntegerField(choices=[(1, 'Đang sử dụng'), (2, 'Đang xây dựng'), (3, 'Không sử dụng')], verbose_name='Loại hiện trạng sử dụng'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='maDoiTuong',
            field=models.CharField(choices=[('KG05', 'KG05')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='kenhmuong',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='loaiNguonNuoc',
            field=models.IntegerField(choices=[(1, 'Khoáng'), (2, 'Nóng'), (3, 'Thường')], verbose_name='Loại nguồn nước'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KM01', 'Giếng nước'), ('KM02', 'Mạch nước')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='nguonnuoc',
            name='ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='loaiRanhGioiNuocMatQuyUoc',
            field=models.IntegerField(choices=[(1, 'Phân chia loại nước mặt'), (2, 'Khép vùng nước mặt')], verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='maDoiTuong',
            field=models.CharField(choices=[('KE06', 'KE06')], max_length=50, verbose_name='Mã đối tượng'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='ranhgioinuocmatquyuoc',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang1',
            field=models.FloatField(verbose_name='Giá trị tháng 1'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang10',
            field=models.FloatField(verbose_name='Giá trị tháng 10'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang11',
            field=models.FloatField(verbose_name='Giá trị tháng 11'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang12',
            field=models.FloatField(verbose_name='Giá trị tháng 12'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang2',
            field=models.FloatField(verbose_name='Giá trị tháng 2'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang3',
            field=models.FloatField(verbose_name='Giá trị tháng 3'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang4',
            field=models.FloatField(verbose_name='Giá trị tháng 4'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang5',
            field=models.FloatField(verbose_name='Giá trị tháng 5'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang6',
            field=models.FloatField(verbose_name='Giá trị tháng 6'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang7',
            field=models.FloatField(verbose_name='Giá trị tháng 7'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang8',
            field=models.FloatField(verbose_name='Giá trị tháng 8'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='giaTriThang9',
            field=models.FloatField(verbose_name='Giá trị tháng 9'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang1',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 1'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang10',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 10'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang11',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 11'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang12',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 12'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang2',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 2'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang3',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 3'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang4',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 4'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang5',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 5'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang6',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 6'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang7',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 7'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang8',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 8'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='huongThang9',
            field=models.CharField(choices=[('N', 'Hướng Bắc'), ('NNE', 'Bắc-Đông Bắc'), ('NE', 'Đông Bắc'), ('ENE', 'Đông-Đông Bắc'), ('E', 'Hướng Đông'), ('ESE', 'Đông-Đông Nam'), ('SE', 'Đông Nam'), ('SSE', 'Nam-Đông Nam'), ('S', 'Hướng Nam'), ('SSW', 'Nam-Tây Nam'), ('SW', 'Tây Nam'), ('WSW', 'Tây-Tây Nam'), ('W', 'Hướng Tây'), ('WNW', 'Tây-Tây Bắc'), ('NW', 'Tây Bắc'), ('NWN', 'Bắc-Tây Bắc')], max_length=50, verbose_name='Hướng tháng 9'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='maSongGioDongChay',
            field=models.CharField(choices=[('TS02', 'TS02')], max_length=50, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='thamSo',
            field=models.IntegerField(choices=[(1, 'Gió'), (2, 'Dòng chảy'), (3, 'Sóng')], verbose_name='Tham số'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='thoigianThuThap',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thu thập'),
        ),
        migrations.AlterField(
            model_name='songgiodongchay',
            name='tramKTTV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuyvan.tramthuthapkttv', verbose_name='Trạm KTTV'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang1',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 1'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang10',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 10'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang11',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 11'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang12',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 12'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang2',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 2'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang3',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 3'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang4',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 4'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang5',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 5'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang6',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 6'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang7',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 7'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang8',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 8'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='giatriThang9',
            field=models.FloatField(blank=True, null=True, verbose_name='Tháng 9'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='maThamSoKTTV',
            field=models.CharField(choices=[('TS01', 'TS01')], max_length=50, verbose_name='Mã trạm'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='thamSo',
            field=models.IntegerField(choices=[(1, 'Nhiệt độ không khí'), (2, 'Độ ẩm không khí'), (3, 'Áp suất không khí'), (4, 'Lượng mưa'), (5, 'Mực nước')], verbose_name='Tham số'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='thoigianThuThap',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thu thập'),
        ),
        migrations.AlterField(
            model_name='thamsokttv',
            name='tramKTTV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuyvan.tramthuthapkttv', verbose_name='Trạm KTTV'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='Mota_TramKTTV',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='giaTriDoChinhXacMatPhang',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá trị độ chính xác mặt phẳng'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='kieuThuThapKTTV',
            field=models.IntegerField(choices=[(1, 'Trạm cố định'), (2, 'Trạm di động')], verbose_name='Kiểu thu thập'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='loaiTramThuThapKTTV',
            field=models.IntegerField(choices=[(1, 'Trạm khí tượng bề mặt'), (2, 'Trạm khí tượng trên cao'), (3, 'Trạm ra đa thời tiết'), (4, 'Trạm khí tượng nông nghiệp'), (5, 'Trạm thủy văn'), (6, 'Trạm hải văn'), (7, 'Trạm định vị sét'), (8, 'Trạm giám sát biến đổi khí hậu'), (9, 'Trạm chuyên đề')], verbose_name='Loại trạm'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='maNhanDang',
            field=models.CharField(max_length=50, verbose_name='Mã nhận dạng'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='maTramKTTV',
            field=models.CharField(choices=[('CR20', 'CR20')], max_length=50, verbose_name='Mã trạm'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='ngayPhienBan',
            field=models.DateTimeField(verbose_name='Ngày phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='nguyenNhanThayDoi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nguyên nhân thay đổi'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='phienBan',
            field=models.IntegerField(verbose_name='Phiên bản'),
        ),
        migrations.AlterField(
            model_name='tramthuthapkttv',
            name='tenTram',
            field=models.CharField(max_length=255, verbose_name='Tên trạm'),
        ),
    ]
