# Generated by Django 3.2.15 on 2022-08-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiStyle',
            fields=[
                ('maLoaiStyle', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã loại style')),
                ('tenLoaiStyle', models.CharField(max_length=100, verbose_name='Tên loại style')),
                ('ghiChu', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
            ],
        ),
        migrations.CreateModel(
            name='LopDuLieu',
            fields=[
                ('maLop', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã lớp')),
                ('tenLop', models.CharField(max_length=50, verbose_name='Tên lớp')),
                ('tenHienThiLop', models.CharField(blank=True, max_length=100, verbose_name='Tên hiển thị lớp')),
                ('publicGeoserver', models.BooleanField(default=False, verbose_name='Public Geoserver')),
                ('pathPublic', models.CharField(blank=True, max_length=200, verbose_name='Path public')),
                ('hienThiLopChuyenDe', models.BooleanField(default=False, verbose_name='Hiển thị lớp chuyên đề')),
                ('thuTuHienThi', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('kieuLop', models.CharField(choices=[(1, 'Lớp điểm'), (2, 'Lớp đường'), (3, 'Lớp vùng'), (4, 'Lớp biểu đồ'), (5, 'Lớp hướng'), (6, 'Lớp khác')], max_length=50, verbose_name='Kiểu lớp')),
            ],
        ),
        migrations.CreateModel(
            name='NhomDuLieu',
            fields=[
                ('maNhom', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nhóm')),
                ('tenNhom', models.CharField(max_length=50, verbose_name='Tên nhóm')),
                ('moTaNhom', models.CharField(blank=True, max_length=500, verbose_name='Mô tả nhóm')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('maStyle', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã style')),
                ('tenStyle', models.CharField(max_length=100, verbose_name='Tên style')),
                ('kieuDinhDangStyle', models.CharField(choices=[(1, 'XML'), (2, 'CSS')], max_length=5, verbose_name='Kiểu định dạng style')),
                ('ngayStyle', models.DateTimeField(blank=True, null=True, verbose_name='Ngày style')),
                ('hienThi', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('styleXML', models.TextField(blank=True, max_length=50000, verbose_name='Style XML')),
                ('styleCSS', models.TextField(blank=True, max_length=50000, verbose_name='Style CSS')),
                ('stylePath', models.FileField(blank=True, null=True, upload_to='styles/', verbose_name='Style file')),
                ('maLoaiStyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.loaistyle')),
                ('maLop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.lopdulieu', verbose_name='Mã lớp')),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('maMetaData', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã MetaData')),
                ('tenMetaData', models.CharField(max_length=50, verbose_name='Tên MetaData')),
                ('XMLMetaData', models.TextField(blank=True, max_length=50000, verbose_name='XML MetaData')),
                ('PathMetaData', models.FileField(upload_to='metadata/', verbose_name='MetaData file')),
                ('maLop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.lopdulieu')),
            ],
        ),
        migrations.CreateModel(
            name='DuLieuDaPhuongTien',
            fields=[
                ('maDulieuMulti', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã dữ liệu')),
                ('tenDuLieu', models.CharField(blank=True, max_length=100, verbose_name='Tên dữ liệu')),
                ('pathDuLieu', models.FileField(upload_to='other/', verbose_name='File dữ liệu')),
                ('ngayDuLieu', models.DateTimeField(blank=True, null=True, verbose_name='Ngày lưu dữ liệu')),
                ('duLieuAnhDaiDien', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('duLieuMoTa', models.BooleanField(default=False, verbose_name='Dữ liệu mô tả')),
                ('maNhanDang', models.CharField(max_length=30, verbose_name='Mã nhận dạng')),
                ('maLop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.lopdulieu', verbose_name='Mã lớp')),
            ],
        ),
    ]
