# Generated by Django 3.2.15 on 2022-08-31 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dulieudaphuongtien',
            name='maLop',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='maLop',
        ),
        migrations.DeleteModel(
            name='NhomDuLieu',
        ),
        migrations.RemoveField(
            model_name='style',
            name='maLoaiStyle',
        ),
        migrations.RemoveField(
            model_name='style',
            name='maLop',
        ),
        migrations.DeleteModel(
            name='DuLieuDaPhuongTien',
        ),
        migrations.DeleteModel(
            name='LoaiStyle',
        ),
        migrations.DeleteModel(
            name='LopDuLieu',
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
