# Generated by Django 3.2.15 on 2022-08-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20220831_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lopdulieu',
            name='kieuLop',
            field=models.IntegerField(choices=[(1, 'Lớp điểm'), (2, 'Lớp đường'), (3, 'Lớp vùng'), (4, 'Lớp biểu đồ'), (5, 'Lớp hướng'), (6, 'Lớp khác')], verbose_name='Kiểu lớp'),
        ),
        migrations.AlterField(
            model_name='style',
            name='kieuDinhDangStyle',
            field=models.IntegerField(choices=[(1, 'XML'), (2, 'CSS')], verbose_name='Kiểu định dạng style'),
        ),
    ]
