export const DIEM_DO_CAO_CONFIG = {
  fields: [
    {
      text: "Thao tác",
      value: "actions",
      sortable: false,
      width: "130px",
      align: "center",
      divider: true,
    },
    {
      text: "Mã",
      value: "id",
      sortable: false,
      align: "center",
      divider: true,
    },
    {
      text: "Phiên bản",
      value: "properties.phienBan",
      sortable: false,
      align: "center",
      divider: true,
      type: { name: "text", value: null, key: "phienBan", required: true },
    },
    {
      text: "Ngày phiên bản",
      value: "properties.ngayPhienBan",
      sortable: false,
      align: "center",
      divider: true,
      type: {
        name: "date",
        value: null,
        key: "ngayPhienBan",
        required: true,
      },
    },
    {
      text: "Giá trị độ chính xác mặt phẳng",
      value: "properties.giaTriDoChinhXacMatPhang",
      sortable: false,
      align: "center",
      divider: true,
      type: {
        name: "number",
        value: null,
        key: "giaTriDoChinhXacMatPhang",
        required: false,
      },
    },
    {
      text: "Nguyên nhân thay đổi",
      value: "properties.nguyenNhanThayDoi",
      sortable: false,
      align: "center",
      divider: true,
      type: {
        name: "textarea",
        value: null,
        key: "nguyenNhanThayDoi",
        required: false,
      },
    },
    {
      text: "Mã đối tượng",
      value: "properties.maDoiTuong",
      sortable: false,
      align: "center",
      divider: true,
      type: {
        name: "select",
        value: ["EA01"],
        key: "maDoiTuong",
        required: true,
      },
    },
    {
      text: "Độ cao",
      value: "properties.doCao",
      sortable: false,
      align: "center",
      divider: true,
      type: {
        name: "number",
        value: null,
        key: "doCao",
        required: true,
      },
    },
  ],
};
