# Generated by Django 3.2.13 on 2022-06-21 07:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDoDacQuocGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('soHieuDiem', models.CharField(max_length=50)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('maDoiTuong', models.CharField(choices=[('BC01', 'Điểm độ cao quốc gia'), ('BC02', 'Điểm tọa độ quốc gia'), ('BC03', 'Điểm tọa độ và độ cao quốc gia'), ('BC04', 'Điểm trọng lực quốc gia')], max_length=50)),
                ('doCao', models.FloatField()),
                ('loaiMoc', models.IntegerField(choices=[(1, 'Chôn'), (2, 'Gắn'), (3, 'Khác')])),
                ('loaiCapHang', models.IntegerField(choices=[(1, 'Cấp cơ sở'), (2, 'Cấp 0'), (3, 'Hạng I'), (4, 'Hạng II'), (5, 'Hạng III')])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiemGocDoDacQuocGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('soHieuDiem', models.CharField(max_length=50)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('maDoiTuong', models.CharField(choices=[('BA01', 'Điểm gốc độ cao quốc gia'), ('BA02', 'Điểm gốc toạ độ quốc gia'), ('BA03', 'Điểm gốc trọng lực quốc gia')], max_length=50)),
                ('doCao', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TramDinhViVeTinhQuocGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhanDang', models.CharField(max_length=50)),
                ('phienBan', models.IntegerField()),
                ('ngayPhienBan', models.DateTimeField()),
                ('giaTriDoChinhXacMatPhang', models.FloatField(blank=True, null=True)),
                ('nguyenNhanThayDoi', models.CharField(blank=True, max_length=250, null=True)),
                ('soHieuDiem', models.CharField(max_length=50)),
                ('GM_Point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4756)),
                ('maDoiTuong', models.CharField(choices=[('BD02', 'BD02')], max_length=50)),
                ('ten', models.CharField(max_length=255)),
                ('loaiTramDinhViVeTinh', models.IntegerField(choices=[(1, 'Trạm tham chiếu cơ sở hoạt động liên tục'), (2, 'Trạm tham chiếu hoạt động liên tục')])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
